### ISSUE TITLE
Apply PseCo to the one-stage detector。Which the one-stage detectordo you choose？yolox?

### ISSUE THREAD

**Issue by CYYAI** [ligang-cs/PseCo#1]

**Comment by ligang-cs** [comment]
We apply the PseCo to the Generalized Focal Loss (GFL) and achieve favorable performance.  The corresponding codes will be released soon. For now, we have no plan to apply the PseCo to YOLOX.

**Comment by baoxin1100** [comment]
> We apply the PseCo to the Generalized Focal Loss (GFL) and achieve favorable performance. The corresponding codes will be released soon. For now, we have no plan to apply the PseCo to YOLOX.

can PseCo be applied to yolov5, looking forward to your reply

**Comment by ligang-cs** [comment]
> > We apply the PseCo to the Generalized Focal Loss (GFL) and achieve favorable performance. The corresponding codes will be released soon. For now, we have no plan to apply the PseCo to YOLOX.
> 
> can PseCo be applied to yolov5, looking forward to your reply

PseCo can be applied to yolov5. Due to limited resource, we only plan to apply the PseCo to Generalized Focal Loss.
