### ISSUE TITLE
P3 P2 特征一致性训练 是怎么用？

### ISSUE THREAD

**Issue by yu1206** [ligang-cs/PseCo#11]
流程图看着就是 不同大小的图像进行训练，P3 和P2 特征怎么综合利用？

**Comment by chen-xing1** [comment]
V2是v1 2倍下采样得来的，所以v2的p2和v1的P3 scale是一样的

**Comment by ligang-cs** [comment]
view 2是对view 1进行2倍下采样得到的，是低分辨率的图片。而检测器对低分辨率的图片，检测性能向来较差。通过Feature-level的对齐，因为view 2和P2-P6 feature分辨率和view 1的P3-P7 feature分辨率是一样的，可以使用相同的pseudo box来同时监督view 2和view 1的FPN features，我们希望低分辨率图片(view 2)，可以产生和高分辨率图片(view 1)一样强的FPN features. 具体的实现麻烦参考代码：[PseCo_frcnn.py](https://github.com/ligang-cs/PseCo/blob/master/ssod/models/PseCo_frcnn.py).
