### ISSUE TITLE
没有标记的数据，怎么得到它的 ground truth

### ISSUE THREAD

**Issue by yu1206** [ligang-cs/PseCo#12]
On unlabeled data, we first
construct a candidate bag for each ground truth g by the traditional IoU-based
strategy, where the IoU threshold t is set to a relatively low value, e.g., 0.4
as default, to contain more proposals

**Comment by shiyongde** [comment]
i fond the code using the unlabled data's bboxes for trainning, is there a step inference all datasets before training ?

       # quality of pseudo label
        precision, recall = get_pseudo_label_quality(
                        gt_bboxes, gt_labels, GT_bboxes, GT_labels)
this  code using GT_bboxes for train, but tools/dataset/semi_coco.py get null box

**Comment by ligang-cs** [comment]
> On unlabeled data, we first construct a candidate bag for each ground truth g by the traditional IoU-based strategy, where the IoU threshold t is set to a relatively low value, e.g., 0.4 as default, to contain more proposals

It is a typo, exactly, "ground truth" should be modified as "pseudo box". On unlabeled data, the ground truth doesn't exist, in contrast, we use pseudo boxes to supervise the model training.

**Comment by ligang-cs** [comment]
> i fond the code using the unlabled data's bboxes for trainning, is there a step inference all datasets before training ?
> 
> ```
>    # quality of pseudo label
>     precision, recall = get_pseudo_label_quality(
>                     gt_bboxes, gt_labels, GT_bboxes, GT_labels)
> ```
> 
> this code using GT_bboxes for train, but tools/dataset/semi_coco.py get null box

The ground truth is not used on unlabeled data. We pass the GT_bbox into the training process just to evaluate the quality of pseudo boxes.

**Comment by devin-ry** [comment]
我很好奇，作者在代码中

**Comment by devin-ry** [comment]
作者怎么从teacher_data拿到["gt_bboxes"]和["gt_labels"] 的，前面也没有定义。`    def foward_unsup_train(self, teacher_data, student_data):
        teacher_img = teacher_data["img"]
        student_img = student_data["img"]

        img_metas_teacher = teacher_data["img_metas"]
        img_metas_student = student_data["img_metas"]

        gt_bboxes, gt_labels = teacher_data["gt_bboxes"], teacher_data["gt_labels"]   `
