### ISSUE TITLE
feature-level consistency learning

### ISSUE THREAD

**Issue by yu1206** [ligang-cs/PseCo#14]
特征一致性学习 在训练的过程中怎么使用的呢？

**Comment by Stephen-Hao** [comment]
我理解就是把两个尺度相同的feature进行类似的L2约束吧？

**Comment by ligang-cs** [comment]
不好意思，文章解释得不太清楚。view 2是对view 1进行2倍下采样得到的，是低分辨率的图片。而检测器对低分辨率的图片，检测性能向来较差。通过Feature-level的对齐，即，使用**相同的**pseudo box来同时监督view 2的FPN features和view 1的FPN features，我们希望低分辨率图片(view 2)，可以产生和高分辨率图片(view 1)一样强的FPN features. 具体的实现麻烦参考代码：[PseCo_frcnn.py](https://github.com/ligang-cs/PseCo/blob/master/ssod/models/PseCo_frcnn.py).
