### ISSUE TITLE
Installing Prettytable

### ISSUE THREAD

**Issue by teodorf-bit** [ligang-cs/PseCo#21]
What version of prettytable are you using, Im haveing problems installing prettytable

Collecting prettytable
  Downloading prettytable-2.5.0-py3-none-any.whl (24 kB)
Requirement already satisfied: matplotlib>=2.1.0 in /ext3/miniconda3/envs/PseCo/lib/python3.6/site-packages (from pycocotools->-r requirements.txt (line 1)) (3.2.2)
Requirement already satisfied: numpy in /ext3/miniconda3/envs/PseCo/lib/python3.6/site-packages (from pycocotools->-r requirements.txt (line 1)) (1.18.5)
Requirement already satisfied: typing-extensions in /ext3/miniconda3/envs/PseCo/lib/python3.6/site-packages (from torch==1.9.0->-r requirements.txt (line 2)) (3.7.4.2)
Collecting dataclasses; python_version < "3.7"
  Downloading dataclasses-0.8-py3-none-any.whl (19 kB)
Requirement already satisfied: pillow>=5.3.0 in /ext3/miniconda3/envs/PseCo/lib/python3.6/site-packages (from torchvision==0.10.0->-r requirements.txt (line 3)) (7.2.0)
Collecting addict
  Downloading addict-2.4.0-py3-none-any.whl (3.8 kB)
Requirement already satisfied: pyyaml in /ext3/miniconda3/envs/PseCo/lib/python3.6/site-packages (from mmcv-full==1.3.9->-r requirements.txt (line 4)) (5.3.1)
Requirement already satisfied: yapf in /ext3/miniconda3/envs/PseCo/lib/python3.6/site-packages (from mmcv-full==1.3.9->-r requirements.txt (line 4)) (0.30.0)
Collecting opencv-python>=3
  Downloading opencv_python-4.6.0.66-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.9 MB)
     |################################| 60.9 MB 33.3 MB/s 
Collecting GitPython==0.3.2.RC1
  Downloading GitPython-0.3.2.RC1.tar.gz (313 kB)
     |################################| 313 kB 100.7 MB/s 
Collecting Parsley==1.2
  Downloading Parsley-1.2.tar.gz (275 kB)
     |################################| 275 kB 101.7 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /ext3/miniconda3/envs/PseCo/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-syt2zakr/Parsley/setup.py'"'"'; __file__='"'"'/tmp/pip-install-syt2zakr/Parsley/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-jjjsdcjj
         cwd: /tmp/pip-install-syt2zakr/Parsley/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-syt2zakr/Parsley/setup.py", line 16, in <module>
        long_description=open("README").read(),
      File "/ext3/miniconda3/envs/PseCo/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3802: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
FATAL:   While performing build: while running engine: exit status 1

**Comment by ligang-cs** [comment]
prettytable==2.5.0
