### ISSUE TITLE
Some problem about the regression weight of unlabeled images

### ISSUE THREAD

**Issue by JCZ404** [ligang-cs/PseCo#3]
Hi, thanks for your such great work, the code is also very excellent ! But I have some problems when I read your code:
In your paper, you said you didn't do the bounding box regression on unlabeled data, but actually you did, I guess this is a writing mistake. What makes me confused is that you said you use the average of multiple positive proposals' IOU to estimate the reliability of a pseudo label, and reweight the regression loss. But, in your code, you calculate the `reg_scale_factor` to reweight the regression loss of the pseudo label, and the calculation of the `reg_scale_factor` is a little bit different from the paper, that is: the sample-wise reweighting without normalization in the paper, but reweight the whole regression loss with normalized `reg_scale_factor` in the code, so I want to ask the reason or the intuition behind this.
<img width="764" alt="image" src="https://user-images.githubusercontent.com/51013927/184476006-66850b7a-e0ea-41bd-bc25-f5d916533374.png">

![image](https://user-images.githubusercontent.com/51013927/184472380-34757cc0-a33a-479e-a285-cb67d4fd7884.png)

**Comment by ligang-cs** [comment]
1. In section 3.1, we construct a vanilla SSOD baseline, where the regression loss is abandoned to stabilize the training. At the early stage of training, some poorly-localized pseudo boxes will incur large regression losses, resulting in "loss NaN". To address this problem, the PseCo employs PCV to suppress low-quality pseudo boxes in the regression loss. With the help of PCV, regression losses can be performed stably.
2.  The calculation of "bbox_weights" (output of the function "compute_PCV") is the same as the description in the paper. The bbox_weights serves as sample-wise weights, while reg_scale_factor is only used to adjust the norm of the regression loss, as to keep the cls and reg losses at the same scale. 
If you have any problem, please feel free to ask.

**Comment by JCZ404** [comment]
Thanks for your kind reply! Another question, I see in your code, you calculate the precision and recall of the pseudo label, and use EMA update to estimate the quality of the pseudo label, I wonder what the recall and precision look like in your training process, I mean what's the range of the precision and recall finally in your work? I found that the calculation of recall seems wrong for sometimes the recall will reach a value larger than 1, for sometimes the TPs may be larger than the num_gts. So I want to confirm this with you. Thanks! Hope to get your reply!
